package com.silence.po;

public class BeUsing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_using.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_using.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer d_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_using.u_place
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String u_place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_using.u_state
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer u_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column be_using.u_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String u_mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_using.id
     *
     * @return the value of be_using.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_using.id
     *
     * @param id the value for be_using.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_using.d_id
     *
     * @return the value of be_using.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_using.d_id
     *
     * @param d_id the value for be_using.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_using.u_place
     *
     * @return the value of be_using.u_place
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getU_place() {
        return u_place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_using.u_place
     *
     * @param u_place the value for be_using.u_place
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setU_place(String u_place) {
        this.u_place = u_place == null ? null : u_place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_using.u_state
     *
     * @return the value of be_using.u_state
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getU_state() {
        return u_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_using.u_state
     *
     * @param u_state the value for be_using.u_state
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setU_state(Integer u_state) {
        this.u_state = u_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column be_using.u_mark
     *
     * @return the value of be_using.u_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getU_mark() {
        return u_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column be_using.u_mark
     *
     * @param u_mark the value for be_using.u_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setU_mark(String u_mark) {
        this.u_mark = u_mark == null ? null : u_mark.trim();
    }
}