package com.silence.po;

import java.util.Date;

public class BuyDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_device.buyer
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String buyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_device.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer d_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_device.b_money
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Float b_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_device.b_time
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Date b_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_device.b_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String b_mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_device.id
     *
     * @return the value of buy_device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_device.id
     *
     * @param id the value for buy_device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_device.buyer
     *
     * @return the value of buy_device.buyer
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_device.buyer
     *
     * @param buyer the value for buy_device.buyer
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_device.d_id
     *
     * @return the value of buy_device.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_device.d_id
     *
     * @param d_id the value for buy_device.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_device.b_money
     *
     * @return the value of buy_device.b_money
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Float getB_money() {
        return b_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_device.b_money
     *
     * @param b_money the value for buy_device.b_money
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setB_money(Float b_money) {
        this.b_money = b_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_device.b_time
     *
     * @return the value of buy_device.b_time
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Date getB_time() {
        return b_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_device.b_time
     *
     * @param b_time the value for buy_device.b_time
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setB_time(Date b_time) {
        this.b_time = b_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_device.b_mark
     *
     * @return the value of buy_device.b_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getB_mark() {
        return b_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_device.b_mark
     *
     * @param b_mark the value for buy_device.b_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setB_mark(String b_mark) {
        this.b_mark = b_mark == null ? null : b_mark.trim();
    }
}