package com.silence.po;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.d_name
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String d_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.d_desc
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String d_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.d_price
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Float d_price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.d_name
     *
     * @return the value of device.d_name
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getD_name() {
        return d_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.d_name
     *
     * @param d_name the value for device.d_name
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setD_name(String d_name) {
        this.d_name = d_name == null ? null : d_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.d_desc
     *
     * @return the value of device.d_desc
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getD_desc() {
        return d_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.d_desc
     *
     * @param d_desc the value for device.d_desc
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setD_desc(String d_desc) {
        this.d_desc = d_desc == null ? null : d_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.d_price
     *
     * @return the value of device.d_price
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Float getD_price() {
        return d_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.d_price
     *
     * @param d_price the value for device.d_price
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setD_price(Float d_price) {
        this.d_price = d_price;
    }
}