package com.silence.po;

import java.util.Date;

public class FixDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fix_device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fix_device.fixer
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String fixer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fix_device.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Integer d_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fix_device.fix_time
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private Date fix_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fix_device.fix_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    private String fix_mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fix_device.id
     *
     * @return the value of fix_device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fix_device.id
     *
     * @param id the value for fix_device.id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fix_device.fixer
     *
     * @return the value of fix_device.fixer
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getFixer() {
        return fixer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fix_device.fixer
     *
     * @param fixer the value for fix_device.fixer
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setFixer(String fixer) {
        this.fixer = fixer == null ? null : fixer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fix_device.d_id
     *
     * @return the value of fix_device.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fix_device.d_id
     *
     * @param d_id the value for fix_device.d_id
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fix_device.fix_time
     *
     * @return the value of fix_device.fix_time
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public Date getFix_time() {
        return fix_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fix_device.fix_time
     *
     * @param fix_time the value for fix_device.fix_time
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setFix_time(Date fix_time) {
        this.fix_time = fix_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fix_device.fix_mark
     *
     * @return the value of fix_device.fix_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public String getFix_mark() {
        return fix_mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fix_device.fix_mark
     *
     * @param fix_mark the value for fix_device.fix_mark
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    public void setFix_mark(String fix_mark) {
        this.fix_mark = fix_mark == null ? null : fix_mark.trim();
    }
}