package com.silence.mapper;

import com.silence.po.BuyDevice;

public interface BuyDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int insert(BuyDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int insertSelective(BuyDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    BuyDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int updateByPrimaryKeySelective(BuyDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int updateByPrimaryKey(BuyDevice record);
}