package com.silence.mapper;

import com.silence.po.FixDevice;

public interface FixDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fix_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fix_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int insert(FixDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fix_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int insertSelective(FixDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fix_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    FixDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fix_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int updateByPrimaryKeySelective(FixDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fix_device
     *
     * @mbggenerated Wed Nov 18 20:22:23 CST 2015
     */
    int updateByPrimaryKey(FixDevice record);
}